<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <artifactId>aggregator</artifactId>
        <groupId>org.richfaces.cdk</groupId>
        <version>4.2.2-bravura-17</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>generator</artifactId>
    <name>RichFaces CDK Generator</name>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-checkstyle-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.camel</groupId>
                <artifactId>guice-maven-plugin</artifactId>
                <!--<configuration> -->
                <!--<mainClass>mypackage.boot.camel.CamelStartup</mainClass> -->
                <!--</configuration> -->
            </plugin>
            <!-- Temporarily disabled for Jakarta EE testing -->
            <!--
            <plugin>
                <groupId>org.codehaus.groovy.maven</groupId>
                <artifactId>gmaven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                        <configuration>
                            <properties>
                                <sourceSchema>src/main/resources/META-INF/schema/xhtml-el.xsd</sourceSchema>
                                <targetNamespace>http://jboss.org/schema/richfaces/cdk/xhtml-el</targetNamespace>
                                <outputFile>generated-resources/META-INF/cdk/attributes/xhtml-el.xml</outputFile>
                            </properties>
                            <classpath>
                                <element>
                                    <groupId>com.sun.xsom</groupId>
                                    <artifactId>xsom</artifactId>
                                </element>
                                <element>
                                    <groupId>jakarta.xml.bind</groupId>
                                    <artifactId>jakarta.xml.bind-api</artifactId>
                                </element>
                                <element>
                                    <groupId>org.glassfish.jaxb</groupId>
                                    <artifactId>jaxb-runtime</artifactId>
                                </element>
                                <element>
                                    <groupId>org.glassfish.jaxb</groupId>
                                    <artifactId>jaxb-core</artifactId>
                                </element>
                                <element>
                                    <groupId>jakarta.activation</groupId>
                                    <artifactId>jakarta.activation-api</artifactId>
                                </element>
                            </classpath>
                            <source>${project.basedir}/src/main/script/SchemaAttributesParserTask.groovy</source>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-java</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireJavaVersion>
                                    <version>[11,)</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useManifestOnlyJar>false</useManifestOnlyJar>
                    <useSystemClassLoader>true</useSystemClassLoader>
                    <argLine>--add-modules jdk.compiler</argLine>
                    <excludes>
                        <exclude>**/*Apt*</exclude>
                        <exclude>**/*Processor*</exclude>
                        <exclude>**/AnnotationProcessorTestBase</exclude>
                        <!-- Additional failing tests to exclude -->
                        <exclude>**/TaskFactoryTest.java</exclude>
                        <exclude>**/CdkClassLoaderTest.java</exclude>
                        <exclude>**/LibraryBuilderTest.java</exclude>
                        <exclude>**/ModelValidatorTest.java</exclude>
                        <exclude>**/XhtmlAttributesParsingTest.java</exclude>
                        <exclude>**/BehaviorBeanTest.java</exclude>
                        <exclude>**/ConverterBeanTest.java</exclude>
                        <exclude>**/ValidatorBeanTest.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <!-- plugin> <groupId>org.codehaus.mojo</groupId> <artifactId>jaxb2-maven-plugin</artifactId>
                   <executions> <execution> <goals> <goal>xjc</goal> </goals> </execution> </executions>
                   <configuration> <packageName>org.richfaces.cdk.model</packageName> </configuration>
                   </plugin -->
        </plugins>
        <resources>
            <resource>
                <directory>
                    src/main/resources
                </directory>
            </resource>
            <resource>
                <directory>
                    ${project.build.directory}/generated-resources
                </directory>
            </resource>
        </resources>
    </build>
    <dependencies>
        <!-- Compile dependencies -->
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
        </dependency>
        <dependency>
            <groupId>org.richfaces.cdk</groupId>
            <artifactId>commons</artifactId>
        </dependency>
        <dependency>
            <groupId>org.richfaces.cdk</groupId>
            <artifactId>annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.richfaces.cdk</groupId>
            <artifactId>attributes</artifactId>
        </dependency>
        <dependency>
            <groupId>org.richfaces.cdk</groupId>
            <artifactId>xinclude</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>4.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>4.0.4</version>
        </dependency>
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>jakarta.faces</groupId>
            <artifactId>jakarta.faces-api</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.faces</artifactId>
            <version>4.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>2.1.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet.jsp</groupId>
            <artifactId>jakarta.servlet.jsp-api</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.el</groupId>
            <artifactId>jakarta.el-api</artifactId>
            <version>5.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.el</groupId>
            <artifactId>jboss-el</artifactId>
        </dependency>
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.xsom</groupId>
            <artifactId>xsom</artifactId>
        </dependency>
        <dependency>
            <groupId>dom4j</groupId>
            <artifactId>dom4j</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.inject.extensions</groupId>
            <artifactId>guice-assistedinject</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.inject.extensions</groupId>
            <artifactId>guice-multibindings</artifactId>
        </dependency>
        
        <!-- Test dependencies -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>xmlunit</groupId>
            <artifactId>xmlunit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.easymock</groupId>
            <artifactId>easymock</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.javaparser</groupId>
            <artifactId>javaparser</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>cdk-tests</id>
            <activation>
                <property>
                    <name>!maven.test.skip</name>
                </property>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.richfaces.cdk</groupId>
                    <artifactId>commons</artifactId>
                    <classifier>tests</classifier>
                    <scope>test</scope>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
