<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>org.richfaces</groupId>
        <artifactId>richfaces-root-parent</artifactId>
        <version>4.2.2.Final</version>
        <relativePath>../../build/parent/pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.richfaces.cdk</groupId>
    <artifactId>parent</artifactId>
    <packaging>pom</packaging>
    <name>RichFaces CDK Parent</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <version.jboss-el>1.0_02.jakarta.bravura.2</version.jboss-el>
    </properties>

    <repositories>
        <repository>
            <id>github-packages</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/martinhickson/jboss-el</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jboss.el</groupId>
                <artifactId>jboss-el</artifactId>
                <version>${version.jboss-el}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>richfaces-checkstyle-report</id>
                        <phase>none</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <scm>
        <connection>scm:git:git://github.com/richfaces/cdk.git</connection>
        <developerConnection>scm:git:git@github.com:richfaces/cdk.git</developerConnection>
        <url>https://github.com/richfaces/cdk</url>
    </scm>
</project>
